### PR TITLE
make user scroll to footer when contact us is clicked

### PR DESCRIPTION
**Pull request by abitsalihu**
Added the feature that when the user clicks on the `contact us` link, they will automatically be scrolled down to the `footer` section.

Below is a video of how the feature will work

`Feature:`

https://user-images.githubusercontent.com/94648837/195146441-9c242026-e9a5-43aa-89e9-e436968a31f7.mp4

### CODE REVIEW

**Comment by abitsalihu** [comment]
Upps my bad, will do it in a minute. :)

**Comment by abitsalihu** [comment]
Added the same logic to all the other pages as well. :)

**Review by anubhav06 — APPROVED** [review]
Great work @abitsalihu. Thank you for your contribution :)

**Comment by anubhav06** [comment]
Closes #5

**Comment by abitsalihu** [comment]
@anubhav06 Thank you as well. :)

**Comment by anubhav06** [comment]
@abitsalihu This doesn't work with the main page and communities page. For rest pages it does work. Kindly fix this

**Comment by anubhav06** [comment]
Sry for the ping, everything's good now 👍🏻

**Pull request merged**
